/* eslint-disable max-lines-per-function */
module.exports = {
  up: (queryInterface) => {
    return queryInterface.bulkInsert(
      `Careers`,
      [
        {
          name: `Administración Pública`,
          code: 21089,
          nem: 0.15,
          ranking: 0.2,
          lang: 0.3,
          math: 0.25,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 35,
          firstScore: 625.8,
          lastScore: 513,
          minScore: 400,
        },
        {
          name: `Bibliotecología y Documentación`,
          code: 21002,
          nem: 0.2,
          ranking: 0.2,
          lang: 0.4,
          math: 0.1,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 35,
          firstScore: 675.3,
          lastScore: 453.6,
          minScore: 400,
        },
        {
          name: `Contador Público y Auditor`,
          code: 21012,
          nem: 0.2,
          ranking: 0.2,
          lang: 0.3,
          math: 0.15,
          ciencHist: 0.15,
          avgMathLang: 450,
          vacancies: 80,
          firstScore: 635.5,
          lastScore: 452.2,
          minScore: 400,
        },
        {
          name: `Ingeniería Comercial`,
          code: 21048,
          nem: 0.1,
          ranking: 0.2,
          lang: 0.3,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 125,
          firstScore: 652.9,
          lastScore: 496.9,
          minScore: 400,
        },
        {
          name: `Ingeniería en Administración Agroindustrial`,
          code: 21015,
          nem: 0.1,
          ranking: 0.2,
          lang: 0.3,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 30,
          firstScore: 628.8,
          lastScore: 461.8,
          minScore: 400,
        },
        {
          name: `Ingeniería en Comercio Internacional`,
          code: 21081,
          nem: 0.1,
          ranking: 0.2,
          lang: 0.3,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 90,
          firstScore: 637.2,
          lastScore: 458.8,
          minScore: 400,
        },
        {
          name: `Ingeniería en Gestión Turística`,
          code: 21082,
          nem: 0.1,
          ranking: 0.2,
          lang: 0.3,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 25,
          firstScore: 659.4,
          lastScore: 448.1,
          minScore: 400,
        },
        {
          name: `Arquitectura`,
          code: 21047,
          nem: 0.15,
          ranking: 0.25,
          lang: 0.2,
          math: 0.2,
          ciencHist: 0.2,
          avgMathLang: 450,
          vacancies: 100,
          firstScore: 640.2,
          lastScore: 527.4,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil en Obras Civiles`,
          code: 21074,
          nem: 0.2,
          ranking: 0.2,
          lang: 0.15,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 100,
          firstScore: 625,
          lastScore: 476.1,
          minScore: 400,
        },
        {
          name: `Ingeniería en Construcción`,
          code: 21032,
          nem: 0.2,
          ranking: 0.2,
          lang: 0.15,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 100,
          firstScore: 716.3,
          lastScore: 476.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil en Prevención de Riesgos y Medioambiente`,
          code: 21087,
          nem: 0.15,
          ranking: 0.35,
          lang: 0.2,
          math: 0.2,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 30,
          firstScore: 615.2,
          lastScore: 462.5,
          minScore: 400,
        },
        {
          name: `Ingeniería en Biotecnología`,
          code: 21073,
          nem: 0.15,
          ranking: 0.25,
          lang: 0.2,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 60,
          firstScore: 675.8,
          lastScore: 540.9,
          minScore: 400,
        },
        {
          name: `Ingeniería en Industria Alimentaria`,
          code: 21039,
          nem: 0.15,
          ranking: 0.25,
          lang: 0.2,
          math: 0.3,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 30,
          firstScore: 680.2,
          lastScore: 464.9,
          minScore: 400,
        },
        {
          name: `Ingeniería en Química`,
          code: 21080,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.15,
          math: 0.3,
          ciencHist: 0.2,
          avgMathLang: 450,
          vacancies: 80,
          firstScore: 606.5,
          lastScore: 451.7,
          minScore: 400,
        },
        {
          name: `Química Industrial`,
          code: 21083,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.15,
          math: 0.3,
          ciencHist: 0.2,
          avgMathLang: 450,
          vacancies: 40,
          firstScore: 596.5,
          lastScore: 4.2,
          minScore: 400,
        },
        {
          name: `Diseño en Comunicación Visual`,
          code: 21024,
          nem: 0.1,
          ranking: 0.4,
          lang: 0.3,
          math: 0.1,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 100,
          firstScore: 706.3,
          lastScore: 440.2,
          minScore: 400,
        },
        {
          name: `Diseño Industrial`,
          code: 21023,
          nem: 0.1,
          ranking: 0.4,
          lang: 0.3,
          math: 0.1,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 65,
          firstScore: 642.2,
          lastScore: 439.9,
          minScore: 400,
        },
        {
          name: `Trabajo Social`,
          code: 21043,
          nem: 0.2,
          ranking: 0.3,
          lang: 0.2,
          math: 0.1,
          ciencHist: 0.2,
          avgMathLang: 450,
          vacancies: 95,
          firstScore: 705.9,
          lastScore: 510.5,
          minScore: 400,
        },
        {
          name: `Bachillerato en CiencHistias de la 0.Ingeniería`,
          code: 21046,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 25,
          firstScore: 586.5,
          lastScore: 504.5,
          minScore: 400,
        },
        {
          name: `Dibujante Proyectista`,
          code: 21071,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 25,
          firstScore: 689.5,
          lastScore: 496.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil en Computación mención Informática `,
          code: 21041,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 130,
          firstScore: 673.5,
          lastScore: 539.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil Industrial`,
          code: 21076,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 200,
          firstScore: 671.5,
          lastScore: 500.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil en CiencHistia de 0.Datos`,
          code: 21049,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 60,
          firstScore: 673.5,
          lastScore: 539.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil Electrónica`,
          code: 21075,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 80,
          firstScore: 657.5,
          lastScore: 500.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Civil en Mecánica`,
          code: 21096,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 90,
          firstScore: 697.5,
          lastScore: 506.8,
          minScore: 400,
        },
        {
          name: `Ingeniería en Geomensura`,
          code: 21031,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 60,
          firstScore: 614.3,
          lastScore: 487.5,
          minScore: 400,
        },
        {
          name: `Ingeniería en Informática`,
          code: 21030,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 105,
          firstScore: 705.5,
          lastScore: 507.5,
          minScore: 400,
        },
        {
          name: `Ingeniería Industrial`,
          code: 21045,
          nem: 0.1,
          ranking: 0.25,
          lang: 0.2,
          math: 0.35,
          ciencHist: 0.1,
          avgMathLang: 450,
          vacancies: 60,
          firstScore: 584.5,
          lastScore: 476.5,
          minScore: 400,
        },
      ],
      {},
    )
  },

  down: (queryInterface) => {
    return queryInterface.bulkDelete(`Careers`, null, {})
  },
}
